## YAML Template.
---
services:
  java_app: 
    container_name: actividad6-back 
    image: todo-list-spring:1.0 
    build: . 
    restart: unless-stopped 
    ports: 
      - 8080:8080
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://actividad6-mysql:3306/academiasoftekk
    depends_on: 
      - java_db

    # servicio java_db, contiene las configuraciones para la base de datos
  java_db:
    container_name: actividad6-mysql
    image: mysql:8.0.33
    ports:
      - 3306:3306 
    environment:
      MYSQL_DATABASE: academiasoftekk #nombre de la base de datos
      MYSQL_ROOT_PASSWORD: 123456 # contraseña de la base de datos
